# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d370437698a060148abc2779038408ba16a3281c5c737dfce0209f9cef4e4c1f74147c7f869e40b5eec9d7540edfc7494033b34ee79bc7b894d227c333f681

test:
  secret_key_base: 5ad8c718a2157215b3081bb0e707a5794f02f2083dfdb67fce4aa6e40dc4059e2bcad56dcaee59781adc1bafd2641ec70d2654514396b8db648f58abba01f444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
